### PR TITLE
function call to isOpen now a property value check

### LINKED ISSUE #3: isOpen is not a function in SerialPort v5, but a property
Bug : when using node HPGL with the last version of node SerialPort, I got this error:
```
return (this.transport && this.transport.isOpen()) === true;
TypeError: this.transport.isOpen is not a function
```
Apparently "isOpen is now a property", starting from version 5.
https://github.com/node-serialport/node-serialport/blob/master/UPGRADE_GUIDE.md

Turning the function call into a property check on line 856 and 963 of hpgl.js fix the issue.

### PR DESCRIPTION
**Pull request by juliendorra**
Fix #3 and makes the module work with the current version of node SerialPort.

### CODE REVIEW

**Comment by djipco** [comment]
Bonjour Julien. Thanks for the PR. However, I would prefer not to break backwards-compatibility. It would be best to first check if `isOpen` is available and, if not, fallback to using `isOpen()`.

**Comment by juliendorra** [comment]
Added a check. Also indicated the dependency in package.json, that could help new users installing.

**Review by djipco — CHANGES_REQUESTED** [review]
This will not work. Checking for `"isOpen" in this.transport` will be true in both cases. I think the best way would be to check if `isOpen` is a function with `typeof isOpen === "function"`.

**Review by djipco — APPROVED** [review]

**Comment by djipco** [comment]
There seems to be a discrepancy between the `serialport` module and the `browser-serialport` module on this regard.

**Comment by djipco** [comment]
This has been fixed in the latest version. Closing.

**Pull request closed without merging**
